import { v2, Vec2 } from "../../engine/geometry.ts";
import { Definitions,Definition, DeepPartial } from "../../engine/mod.ts";
import { cloneDeep, mergeDeep } from "../../engine/utils.ts";
import { FistRig,WeaponsArmRig,WeaponsRig, ItemQuality, tracers, WeaponRig, WeaponAssets } from "../../others/item.ts";
import { type BulletDef, BulletReflection, InventoryItemType, ItemQualitySettings } from "../utils.ts";
export enum FireMode{
    Auto,
    Single,
    Burst
}
export interface DualAdditional{dual_offset:number}
export interface GasParticle{
    count:number
    size:{
        min:number
        max:number
    }
    speed:{
        min:number
        max:number
    }
    life_time:number
    direction_variation:number
}
export enum GunClasses{
    Pistol,
    Shotgun,
    Sniper,
    Assault,
    SMG,
    DMR,
    LMG,
    Miscellaneous,
    Magic,
}
export interface MuzzleFlash{
    sprite:string
}
export const MuzzleFlash={
    normal:{
        sprite:"muzzle_flash_1",
    }
}
export type GunDef={
    bullet?:{
        def:BulletDef
        count?:number
    }
    projectile?:{
        def:string
        count?:number
        angular_speed?:number
        speed?:number
    }
    mana_consume?:number
    ammoSpawnAmount?:number
    ammoSpawn?:string
    fireDelay:number
    switchDelay?:number
    spread?:number
    lenght:number
    jitterRadius?:number
    fireMode?:FireMode
    burst?:{
        delay:number
        sequence:number
    }
    speed_mod?:number
    size:number
    ammoType:string
    class:GunClasses
    quality:ItemQuality
    muzzleFlash?:MuzzleFlash
    reload?:{
        capacity:number
        delay:number
        shotsPerReload?:number
        reload_alt?:{
            delay:number
            shotsPerReload?:number
        }
        ammo_consume?:number
    }
    recoil?:{
        duration:number
        speed:number
    }
    arms?:FistRig
    image?:WeaponRig
    assets?:WeaponAssets
    caseParticle?:{
        position:Vec2
        at_begin?:boolean
        frame?:string
    }
    gasParticles?:GasParticle
    dual?:DeepPartial<GunDef>&DualAdditional
    item_type?:InventoryItemType.gun
}&({
    dual_from?:undefined
}|{
    dual_from:string
    dual_offset:number
})&Definition

export const Guns=new Definitions<GunDef,{}>((g)=>{
    g.item_type=InventoryItemType.gun
    if(g.dual&&!g.dual_from){
        const dd=mergeDeep({},g,g.dual,{dual_from:g.idString}) as GunDef
        dd.idString=dd.idString+"_dual"
        Guns.insert(dd)
    }
})
export const GunsConstructors={
    extends(gun:GunDef,variant:DeepPartial<GunDef>):GunDef{
        return mergeDeep({}as GunDef,gun,variant)as GunDef
    },
    create_variant(gun:GunDef,quality:ItemQuality,params:{
        damage_increment?:number
        capacity_increment?:number
    }):GunDef{
        const ret=cloneDeep(gun)
        ret.idString=ItemQualitySettings[quality].name+"_"+ret.idString
        ret.quality=quality
        if(!ret.assets){
            ret.assets={}
        }
        ret.assets.item=gun.assets?.item??gun.idString
        ret.assets.item_tint=gun.assets?.item_tint
        ret.assets.item=gun.assets?.world??gun.idString+"_world"
        ret.assets.world_tint=gun.assets?.world_tint
        if(ret.bullet){
            if(params.damage_increment){
                ret.bullet.def.damage+=params.damage_increment
            }
        }
        return ret
    }
}

export const GasParticles={
    shotgun:{
        count:7,
        size:{
            min:0.5,
            max:1.2
        },
        speed:{
            min:1,
            max:2
        },
        life_time:0.9,
        direction_variation:0.4
    } satisfies GasParticle,
    sniper:{
        count:8,
        size:{
            min:0.6,
            max:1.4
        },
        speed:{
            min:1,
            max:2
        },
        life_time:1.1,
        direction_variation:0.43
    } satisfies GasParticle,
    automatic:{
        count:1, 
        size:{
            min:0.8,
            max:1
        },
        speed:{
            min:1,
            max:2
        },
        life_time:0.7,
        direction_variation:0.2
    } satisfies GasParticle,
    pistols:{
        count:2,
        size:{
            min:0.7,
            max:0.8
        },
        speed:{
            min:1,
            max:2
        },
        life_time:0.7,
        direction_variation:0.2
    } satisfies GasParticle
}

Guns.insert(
    {
        idString:"m9",
        fireDelay:0.2,
        spread:0.7,
        lenght:0.8,
        size:6,
        ammoType:"9mm",
        fireMode:FireMode.Single,
        class:GunClasses.Pistol,
        quality:ItemQuality.Common,
        ammoSpawnAmount:45,
        bullet:{
            def:{
                damage:11,
                radius:0.02,
                range:100,
                falloff:0.8,
                speed:31,
                obstacleMult:1.2,
                tracer:tracers.small
            }
        },
        reload:{
            delay:2,
            capacity:15,
        },
        recoil:{
            duration:0.34,
            speed:0.8
        },
        speed_mod:0.98,
        arms:WeaponsArmRig[3],
        assets:{
            world:"weapon_small_world",
            world_tint:0xaaaaaa
        },
        gasParticles:GasParticles.pistols,
        muzzleFlash:MuzzleFlash.normal,
        image:WeaponsRig[0],
        dual:{
            dual_offset:0.2,
            fireDelay:0.15,
            reload:{
                capacity:30,
                delay:3
            }
        }
    },
    {
        idString:"yellow_laser_gun",
        fireDelay:0.2,
        spread:0.7,
        lenght:0.8,
        size:6,
        ammoType:"9mm",
        fireMode:FireMode.Single,
        class:GunClasses.Pistol,
        quality:ItemQuality.Common,
        ammoSpawnAmount:25,
        bullet:{
            def:{
                damage:11,
                radius:0.02,
                range:100,
                falloff:0.8,
                speed:31,
                obstacleMult:1.2,
                tracer:tracers.small,
                reflection:BulletReflection.All
            }
        },
        reload:{
            delay:2.5,
            capacity:15,
        },
        recoil:{
            duration:0.34,
            speed:0.8
        },
        speed_mod:0.98,
        arms:WeaponsArmRig[3],
        gasParticles:GasParticles.pistols,
        muzzleFlash:MuzzleFlash.normal,
        image:WeaponsRig[0],
        assets:{
            world:"weapon_small_world",
            world_tint:0xaaaaaa
        },
        dual:{
            dual_offset:0.2,
            fireDelay:0.15,
            reload:{
                capacity:30,
                delay:4
            }
        }
    },
    {
        idString:"pfeifer_zeliska",
        fireDelay:1.4,
        spread:0.7,
        lenght:0.8,
        size:6,
        ammoType:"308sub",
        fireMode:FireMode.Single,
        class:GunClasses.Pistol,
        quality:ItemQuality.Legendary,
        ammoSpawnAmount:25,
        bullet:{
            def:{
                damage:60,
                radius:0.02,
                range:230,
                falloff:0.7,
                speed:38,
                obstacleMult:1.7,
                tracer:tracers.large
            }
        },
        reload:{
            delay:3.2,
            capacity:5,
        },
        recoil:{
            duration:1.45,
            speed:0.25
        },
        speed_mod:0.9,
        arms:WeaponsArmRig[3],
        muzzleFlash:MuzzleFlash.normal,
        image:WeaponsRig[0],
        dual:{
            dual_offset:0.2,
            fireDelay:0.8,
            reload:{
                capacity:10,
                delay:6
            }
        }
    },
    {
        idString:"ak47",
        fireDelay:0.15,
        switchDelay:0.6,
        spread:5,
        lenght:1.2,
        size:4,
        ammoType:"762mm",
        ammoSpawnAmount:90,
        class:GunClasses.Assault,
        quality:ItemQuality.Rare,
        bullet:{
            def:{
                damage:10,
                radius:0.014,
                range:170,
                speed:40,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:2.5,
            capacity:30
        },
        recoil:{
            duration:0.12,
            speed:0.75
        },
        speed_mod:0.97,
        gasParticles:GasParticles.automatic,
        muzzleFlash:MuzzleFlash.normal,
        arms:WeaponsArmRig[0],
        image:WeaponsRig[0]
    },
    {
        idString:"ar15",
        fireDelay:0.1,
        switchDelay:0.7,
        spread:8,
        lenght:0.7,
        size:4,
        ammoType:"556mm",
        ammoSpawnAmount:90,
        class:GunClasses.Assault,
        quality:ItemQuality.Rare,
        bullet:{
            def:{
                damage:10,
                radius:0.014,
                range:190,
                falloff:0.7,
                speed:42,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:2.5,
            capacity:30
        },
        recoil:{
            duration:0.14,
            speed:0.75
        },
        muzzleFlash:MuzzleFlash.normal,
        speed_mod:0.95,
        gasParticles:GasParticles.automatic,
        arms:WeaponsArmRig[0],
        assets:{
            world:"weapon_medium_world",
            world_tint:0x12111f
        },
        image:{
            position:v2.new(0.6,0.0),
            rotation:0
        },
    },
    {
        idString:"famas",
        fireDelay:0.4,
        switchDelay:0.7,
        fireMode:FireMode.Burst,
        burst:{
            delay:0.1,
            sequence:3
        },
        spread:1.5,
        lenght:0.7,
        size:4,
        ammoType:"556mm",
        ammoSpawnAmount:90,
        class:GunClasses.Assault,
        quality:ItemQuality.Epic,
        bullet:{
            def:{
                damage:11,
                radius:0.014,
                range:190,
                falloff:0.7,
                speed:42,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:2.5,
            capacity:25
        },
        recoil:{
            duration:0.4,
            speed:0.5
        },
        speed_mod:0.95,
        gasParticles:GasParticles.automatic,
        arms:WeaponsArmRig[0],
        assets:{
            world:"weapon_medium_world",
            world_tint:0x12111f
        },
        image:{
            position:v2.new(0.6,0.0),
            rotation:0
        },
    },
    {
        idString:"mp5",
        fireDelay:0.14,
        switchDelay:0.7,
        spread:2,
        lenght:0.87,
        size:4,
        ammoType:"9mm",
        ammoSpawnAmount:96,
        class:GunClasses.Assault,
        quality:ItemQuality.Uncommon,
        bullet:{
            def:{
                damage:9,
                radius:0.014,
                range:160,
                falloff:0.9,
                speed:37,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:2,
            capacity:32
        },
        recoil:{
            duration:0.11,
            speed:0.8
        },
        speed_mod:1,
        gasParticles:GasParticles.automatic,
        muzzleFlash:MuzzleFlash.normal,
        arms:WeaponsArmRig[2],
        image:{
            position:v2.new(0.5,0.0),
            rotation:0
        },
    },
    {
        idString:"vector",
        fireDelay:0.03,
        switchDelay:0.7,
        spread:2,
        lenght:0.6,
        size:4,
        ammoType:"9mm",
        ammoSpawnAmount:99,
        class:GunClasses.Assault,
        quality:ItemQuality.Mythic,
        bullet:{
            def:{
                damage:6,
                radius:0.014,
                range:60,
                criticalMult:1.5,
                speed:40,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:1.7,
            capacity:33
        },
        recoil:{
            duration:0.07,
            speed:0.77
        },
        speed_mod:1,
        gasParticles:GasParticles.pistols,
        muzzleFlash:MuzzleFlash.normal,
        arms:WeaponsArmRig[2],
        assets:{
            world:"weapon_medium_world",
            world_tint:0x3f3a2f
        },
        image:{
            position:v2.new(0.6,0.0),
            rotation:0
        },
    },
    {
        idString:"uzi",
        fireDelay:0.03,
        switchDelay:0.7,
        spread:9,
        lenght:0.68,
        size:4,
        ammoType:"9mm",
        ammoSpawnAmount:96,
        class:GunClasses.Assault,
        quality:ItemQuality.Rare,
        bullet:{
            def:{
                damage:6,
                radius:0.014,
                range:35,
                speed:34,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:1.7,
            capacity:32
        },
        recoil:{
            duration:0.07,
            speed:0.77
        },
        speed_mod:1,
        gasParticles:GasParticles.automatic,
        arms:WeaponsArmRig[2],
        assets:{
            world:"weapon_small_world",
            world_tint:0x12111f
        },
        image:{
            position:v2.new(0.6,0.0),
            scale:1.2,
            rotation:0
        },
    },
    {
        idString:"kar98k",
        fireDelay:1.1,
        spread:0.4,
        lenght:1.26,
        size:4.5,
        ammoType:"762mm",
        ammoSpawnAmount:20,
        fireMode:FireMode.Single,
        class:GunClasses.Sniper,
        quality:ItemQuality.Mythic,
        bullet:{
            def:{
                damage:45,
                radius:0.02,
                range:210,
                falloff:0.8,
                criticalMult:1.1,
                speed:50,
                tracer:tracers.large
            }
        },
        reload:{
            delay:0.9,
            capacity:5,
            shotsPerReload:1,
            reload_alt:{
                delay:2.7,
            }
        },
        recoil:{
            duration:1.25,
            speed:0.4
        },
        speed_mod:0.95,
        arms:WeaponsArmRig[1],
        image:{
            position:v2.new(0.6,0.04),
            rotation:0
        },
        gasParticles:GasParticles.sniper,
        muzzleFlash:MuzzleFlash.normal,
        caseParticle:{
            position:v2.new(0.6,0.3)
        }
    },
    {
        idString:"awp",
        fireDelay:1.1,
        spread:0.5,
        lenght:0.9,
        size:6,
        ammoType:"762mm",
        fireMode:FireMode.Single,
        class:GunClasses.Sniper,
        quality:ItemQuality.Mythic,
        ammoSpawnAmount:30,
        bullet:{
            def:{
                damage:52,
                radius:0.025,
                range:220,
                falloff:0.7,
                speed:55,
                criticalMult:1.1,
                tracer:tracers.xl,
                obstacleMult:1.5,
            }
        },
        reload:{
            delay:3.3,
            capacity:10,
            shotsPerReload:10,
        },
        recoil:{
            duration:1.37,
            speed:0.65
        },
        speed_mod:0.9,
        arms:WeaponsArmRig[1],
        image:{
            position:v2.new(0.6,0.04),
            rotation:0
        },
        gasParticles:GasParticles.sniper,
        muzzleFlash:MuzzleFlash.normal,
        caseParticle:{
            position:v2.new(0.6,0.3)
        }
    },
    {
        idString:"awms",
        fireDelay:1.4,
        spread:0.7,
        lenght:1,
        size:6,
        ammoType:"308sub",
        fireMode:FireMode.Single,
        class:GunClasses.Sniper,
        quality:ItemQuality.Legendary,
        ammoSpawnAmount:25,
        bullet:{
            def:{
                damage:90,
                radius:0.02,
                range:230,
                falloff:0.7,
                speed:38,
                criticalMult:1.2,
                obstacleMult:1.7,
                tracer:tracers.large
            }
        },
        reload:{
            delay:3.9,
            capacity:5,
        },
        recoil:{
            duration:1.45,
            speed:0.25
        },
        speed_mod:0.9,
        arms:WeaponsArmRig[1],
        image:{
            position:v2.new(0.6,0.04),
            rotation:0
        },
        gasParticles:GasParticles.sniper,
        muzzleFlash:MuzzleFlash.normal,
        caseParticle:{
            position:v2.new(0.6,0.3)
        }
    },
    {
        idString:"m870",
        fireDelay:0.8,
        spread:6,
        lenght:0.9,
        ammoType:"12g",
        ammoSpawnAmount:10,
        jitterRadius:0.5,
        size:4.3,
        fireMode:FireMode.Single,
        class:GunClasses.Shotgun,
        quality:ItemQuality.Rare,
        bullet:{
            def:{
                damage:9,
                radius:0.014,
                speed:24,
                range:25,
                falloff:0.8,
                criticalMult:1.2,
                tracer:tracers.small
            },
            count:9
        },
        reload:{
            delay:0.8,
            capacity:5,
            shotsPerReload:1,
        },
        recoil:{
            duration:1,
            speed:0.55
        },
        speed_mod:0.95,
        gasParticles:GasParticles.shotgun,
        arms:WeaponsArmRig[0],
        image:{
            position:v2.new(0.5,0),
            rotation:0
        },
        caseParticle:{
            position:v2.new(0.8,0.3)
        },
        muzzleFlash:MuzzleFlash.normal
    },
    {
        idString:"spas12",
        fireDelay:0.7,
        spread:3,
        lenght:1,
        ammoType:"12g",
        ammoSpawnAmount:18,
        jitterRadius:0.14,
        class:GunClasses.Shotgun,
        quality:ItemQuality.Epic,
        size:4.5,
        fireMode:FireMode.Single,
        muzzleFlash:MuzzleFlash.normal,
        bullet:{
            def:{
                damage:7,
                radius:0.012,
                speed:32,
                range:54,
                criticalMult:1.1,
                falloff:0.65,
                tracer:tracers.small
            },
            count:9
        },
        reload:{
            delay:0.6,
            capacity:9,
            shotsPerReload:1,
        },
        recoil:{
            duration:1,
            speed:0.6
        },
        speed_mod:0.95,
        gasParticles:GasParticles.shotgun,
        arms:WeaponsArmRig[0],
        image:{
            position:v2.new(0.4,0.01),
            rotation:0
        },
        caseParticle:{
            position:v2.new(0.6,0.3)
        }
    },
    {
        idString:"hp18",
        fireDelay:0.6,
        switchDelay:0.7,
        spread:11,
        lenght:0.65,
        ammoType:"12g",
        ammoSpawnAmount:15,
        jitterRadius:0.2,
        class:GunClasses.Shotgun,
        quality:ItemQuality.Uncommon,
        size:3.8,
        fireMode:FireMode.Auto,
        bullet:{
            def:{
                damage:5,
                radius:0.01,
                speed:25,
                falloff:0.7,
                range:26,
                criticalMult:1.2,
                tracer:tracers.tiny
            },
            count:14
        },
        reload:{
            delay:0.8,
            capacity:7,
            shotsPerReload:1,
        },
        recoil:{
            duration:0.4,
            speed:0.75
        },
        speed_mod:1,
        gasParticles:GasParticles.shotgun,
        arms:WeaponsArmRig[0],
        assets:{
            world:"weapon_medium_world",
            world_tint:0x12111f
        },
        image:{
            position:v2.new(0.45,0.0),
            rotation:0
        },
    },
    {
        idString:"rpg7",
        fireDelay:1,
        spread:0.2,
        lenght:1,
        size:6,
        ammoType:"explosive_ammo",
        fireMode:FireMode.Single,
        class:GunClasses.Miscellaneous,
        quality:ItemQuality.Legendary,
        ammoSpawnAmount:11,
        gasParticles:{
            count:10,
            life_time:1.2,
            speed:{
                min:1,
                max:2
            },
            direction_variation:0.4,
            size:{
                min:0.6,
                max:2,
            }
        },
        bullet:{
            def:{
                damage:20,
                radius:0.2,
                range:220,
                falloff:0.5,
                on_hit_explosion:"rocket_explosion",
                speed:22,
                criticalMult:1.2,
                obstacleMult:3,
                tracer:{
                    height:2,
                    width:2,
                    particles:{
                        frame:1
                    },
                    proj:{
                        img:2,
                        width:4,
                        height:4,
                    },
                }
            }
        },
        reload:{
            delay:2,
            capacity:1,
        },
        recoil:{
            duration:1.45,
            speed:0.25
        },
        speed_mod:0.5,
    },
    {
        idString:"m2_2",
        fireDelay:0.07,
        spread:3,
        lenght:1,
        size:6,
        ammoType:"gasoline",
        fireMode:FireMode.Auto,
        class:GunClasses.Miscellaneous,
        quality:ItemQuality.Mythic,
        ammoSpawnAmount:15.2,
        bullet:{
            def:{
                damage:1,
                effect:[{
                    id:"fire",
                    time:5
                }],
                radius:0.2,
                range:28,
                falloff:0.4,
                speed:30,
                criticalMult:4,
                obstacleMult:5,
                reflection:BulletReflection.None,
                tracer:{
                    height:6,
                    width:6,
                    proj:{
                        img:0,
                        height:1,
                        width:1
                    },
                },
            },
            count:3
        },
        reload:{
            delay:5,
            capacity:7.6,
            ammo_consume:0.03,
        },
        recoil:{
            duration:1.45,
            speed:0.46
        },
        speed_mod:0.6,
    },
    /*{
        idString:"bomb_staff",
        fireDelay:0.9,
        spread:3,
        lenght:0.7,
        size:3.8,
        ammoType:"mana",
        ammoSpawnAmount:2,
        ammoSpawn:"purple_pills",
        mana_consume:20,
        class:GunClasses.Magic,
        quality:ItemQuality.Legendary,
        fireMode:FireMode.Single,
        projectile:{
            def:"bomb_staff_projectile",
            angular_speed:0,
            speed:11
        },
        recoil:{
            duration:1,
            speed:0.6
        },
        speed_mod:0.97,
    },
    {
        idString:"fireball_staff",
        fireDelay:0.5,
        spread:4,
        lenght:0.7,
        size:3.7,
        ammoType:"mana",
        ammoSpawnAmount:2,
        ammoSpawn:"purple_pills",
        mana_consume:5,
        class:GunClasses.Magic,
        quality:ItemQuality.Mythic,
        fireMode:FireMode.Auto,
        projectile:{
            def:"fireball_projectile",
            angular_speed:0,
            speed:14
        },
        recoil:{
            duration:0.6,
            speed:0.8
        },
        speed_mod:0.97,
    },*/
)
/*Guns.insert(
    GunsConstructors.create_variant(Guns.getFromString("ak47"),ItemQuality.Uncommon,{
        damage_increment:-0.5
    })
)*/