import { Definitions,Definition } from "../../engine/mod.ts"
import { tracers } from "../../others/item.ts";
import { BulletDef } from "../utils.ts";

export type ExplosionDef={
    size:{
        begin:number
        end:number
    }
    tint:string
    damage:number
    bullet?:{
        def:BulletDef
        count:number
    }
    sounds?:{
        normal:string
    }
    projectiles?:{
        def:string
        count:number
        speed:number
        angSpeed:number
        randomAng:number
    }
}&Definition
export const Explosions=new Definitions<ExplosionDef,null>((_v)=>{})
Explosions.insert(
    {
        idString:"barrel_explosion",
        tint:"#445",
        size:{
            begin:2,
            end:3
        },
        damage:100,
        bullet:{
            def:{
                damage:7,
                radius:0.02,
                speed:20,
                range:25,
                tracer:tracers.black_projectile
            },
            count:6
        }
    },
    {
        idString:"rocket_explosion",
        tint:"#445",
        size:{
            begin:1,
            end:2
        },
        sounds:{
            normal:"explosion_1"
        },
        damage:90,
    },
    {
        idString:"frag_grenade_explosion",
        tint:"#355",
        size:{
            begin:1.5,
            end:2
        },
        damage:99,
        bullet:{
            def:{
                damage:7,
                radius:0.0125,
                speed:18,
                range:8,
                tracer:tracers.medium
            },
            count:5
        },
        sounds:{
            normal:"explosion_1"
        },
    },
    {
        idString:"mirv_grenade_explosion",
        tint:"#09e",
        size:{
            begin:1.6,
            end:2.2
        },
        damage:110,
        bullet:{
            def:{
                damage:7,
                radius:0.0125,
                speed:18,
                range:8,
                tracer:tracers.mirv
            },
            count:5
        },
        projectiles:{
            count:6,
            def:"submirv_grenade",
            speed:1,
            angSpeed:9,
            randomAng:1
        },
        sounds:{
            normal:"explosion_1"
        },
    },
    {
        idString:"submirv_grenade_explosion",
        tint:"#09e",
        size:{
            begin:0.1,
            end:0.2
        },
        damage:35,
        bullet:{
            def:{
                damage:7,
                radius:0.0125,
                speed:18,
                range:8,
                tracer:tracers.mirv
            },
            count:5
        },
    },
)