import { Definitions,Definition, v2 } from "../../engine/mod.ts"
import { DefaultFistRig, FistRig, ItemQuality, WeaponAssets, WeaponRig } from "../../others/item.ts"
import { InventoryItemType } from "../utils.ts"

export type ProjectileDef={
    explosion?:string

    gravity:number
    radius:number
    zBaseScale:number
    zScaleAdd:number

    decays:{
        ground_speed:number
        ground_rotation:number
    }

    cook?:{
        allow_hand:boolean
        fuse_time:number
    }
    throw_max_speed?:number

    frames:{
        world:string
    }

    destroy_on_collide?:boolean
    collision_damage?:number

    speed_mod?:number

    arms?:FistRig
    image?:WeaponRig
    assets?:WeaponAssets

    quality:ItemQuality
    item_type?:InventoryItemType.projectile
}&Definition
export const Projectiles=new Definitions<ProjectileDef,{}>((v)=>{
    v.item_type=InventoryItemType.projectile
})
const GrenadeRig={
    position:v2.new(0.5,0.18),
    rotation:0.2
}
Projectiles.insert(
    {
        idString:"frag_grenade",
        gravity:0.7,
        radius:0.5,
        zBaseScale:0.6,
        zScaleAdd:0.6,
        decays:{
            ground_rotation:2,
            ground_speed:2
        },
        cook:{
            allow_hand:true,
            fuse_time:6
        },
        throw_max_speed:15,
        explosion:"frag_grenade_explosion",
        frames:{
            world:"proj_frag"
        },
        speed_mod:1,
        arms:DefaultFistRig,
        image:GrenadeRig,
        quality:ItemQuality.Common
    },
    //Mirv
    {
        idString:"mirv_grenade",
        gravity:0.7,
        radius:0.5,
        zBaseScale:1,
        zScaleAdd:0.6,
        decays:{
            ground_rotation:2,
            ground_speed:2
        },
        cook:{
            allow_hand:true,
            fuse_time:6
        },
        explosion:"mirv_grenade_explosion",
        throw_max_speed:15,
        frames:{
            world:"proj_mirv"
        },
        arms:DefaultFistRig,
        image:GrenadeRig,
        quality:ItemQuality.Common
    },
    {
        idString:"submirv_grenade",
        gravity:1.2,
        radius:0.5,
        zBaseScale:1,
        zScaleAdd:0.6,
        decays:{
            ground_rotation:3,
            ground_speed:3
        },
        cook:{
            allow_hand:false,
            fuse_time:2
        },
        explosion:"submirv_grenade_explosion",
        frames:{
            world:"proj_submirv"
        },
        arms:DefaultFistRig,
        image:GrenadeRig,
        quality:ItemQuality.Common
    },
    {
        idString:"bomb_staff_projectile",
        gravity:0.45,
        radius:0.3,
        zBaseScale:0.5,
        zScaleAdd:0.6,
        decays:{
            ground_rotation:1,
            ground_speed:1
        },
        destroy_on_collide:true,
        cook:{
            allow_hand:false,
            fuse_time:1
        },
        explosion:"frag_grenade_explosion",
        frames:{
            world:"proj_bomb_staff"
        },
        arms:DefaultFistRig,
        image:GrenadeRig,
        quality:ItemQuality.Common
    },
    {
        idString:"fireball_projectile",
        gravity:0.46,
        radius:0.3,
        zBaseScale:0.5,
        zScaleAdd:0.6,
        decays:{
            ground_rotation:1,
            ground_speed:1
        },
        destroy_on_collide:true,
        collision_damage:30,
        cook:{
            allow_hand:false,
            fuse_time:1
        },
        frames:{
            world:"proj_fireball"
        },
        arms:DefaultFistRig,
        image:GrenadeRig,
        quality:ItemQuality.Common
    },
)