import { v2 } from "../../engine/geometry.ts";
import { FloorType } from "../../others/terrain.ts";
import { BiomeDef, type MapDef } from "./base.ts";
export const NormalBiome:BiomeDef={
    floors:{

    },
    assets:[
        "normal"
    ],
    ambient:{
        particles:["leaf_01_particle_1"],
        rain:true,
        sound:"storm_ambience"
    }
}
export const NormalMap:MapDef={
    loot_tables:{
        //Guns
        "common_guns":[
            {item:"m9",weight:5},
        ],
        "uncommon_guns":[
            {item:"mp5",weight:1.4},
            {item:"hp18",weight:1},
        ],
        "rare_guns":[
            {item:"ak47",weight:3},
            {item:"ar15",weight:2},
            {item:"m870",weight:2},
        ],
        "epic_guns":[
            {item:"famas",weight:6},
            {item:"spas12",weight:3},
        ],
        "mythic_guns":[
            {item:"vector",weight:6},
            {item:"kar98k",weight:6},
            {item:"awp",weight:0.5},
            {item:"m2_2",weight:0.1},
        ],
        "legendary_guns":[
            {item:"awms",weight:1},
            {item:"pfeifer_zeliska",weight:1},
            {item:"rpg7",weight:0.8},
        ],
        "guns":[
            {table:"common_guns",weight:27},
            {table:"uncommon_guns",weight:25},
            {table:"rare_guns",weight:17},
            {table:"epic_guns",weight:1},
            {table:"mythic_guns",weight:0.1},
            {table:"legendary_guns",weight:0.01}
        ],
        "melees":[
            {item:"axe",weight:10},
            {item:"sledgehammer",weight:1},
        ],
        "special_guns":[
            {table:"uncommon_guns",weight:29},
            {table:"rare_guns",weight:20},
            {table:"epic_guns",weight:3},
            {table:"mythic_guns",weight:0.7},
            {table:"legendary_guns",weight:0.3}
        ],
        //Consumibles
        "consumibles":[
            {"item":"bandage","count":5,"weight":1000},
            {"item":"yellow_soda","count":1,"weight":950},
            {"item":"blue_soda","count":2,"weight":700},
            {"item":"inhaler","count":1,"weight":400},
            {"item":"medikit","count":1,"weight":350},
            {"item":"blue_potion","count":1,"weight":240},
            {"item":"small_red_crystal","count":4,"weight":130},
            {"item":"red_soda","count":1,"weight":110},
            {"item":"red_crystal","count":2,"weight":60},
            {"item":"yellow_pills","count":1,"weight":4},
            {"item":"blue_pills","count":1,"weight":4},
            {"item":"red_pills","count":1,"weight":2.5},
            {"item":"green_soda","count":1,"weight":3},
            {"item":"black_soda","count":1,"weight":1.25}
        ],
        "special_consumibles":[
            {"item":"bandage","count":10,"weight":1000},
            {"item":"yellow_soda","count":2,"weight":950},
            {"item":"blue_soda","count":3,"weight":700},
            {"item":"inhaler","count":2,"weight":400},
            {"item":"medikit","count":1,"weight":350},
            {"item":"blue_potion","count":2,"weight":240},
            {"item":"small_red_crystal","count":6,"weight":130},
            {"item":"red_soda","count":2,"weight":110},
            {"item":"red_crystal","count":2,"weight":60},
            {"item":"yellow_pills","count":1,"weight":4},
            {"item":"blue_pills","count":1,"weight":4},
            {"item":"red_pills","count":1,"weight":2.5},
            {"item":"green_soda","count":2,"weight":3},
            {"item":"black_soda","count":2,"weight":1.25}
        ],
        "mana":[
            {item:"purple_soda",count:2,weight:100},
            {item:"purple_potion",count:1,weight:40},
            {item:"purple_pills",count:1,weight:3},
        ],
        //Ammos
        "ammos":[
            {item:"12g",count:10,weight:5},
            {item:"9mm",count:60,weight:5},
            {item:"22lr",count:60,weight:5},
            {item:"762mm",count:60,weight:5},
            {item:"556mm",count:60,weight:5},
            {item:"50cal",count:20,weight:0.1},
            {item:"308sub",count:5,weight:0.05},
            {item:"gasoline",count:5,weight:0.05},
            {item:"explosive_ammo",count:2,weight:0.05},
        ],
        "special_ammos":[
            {item:"12g",count:15,weight:5},
            {item:"9mm",count:80,weight:5},
            {item:"22lr",count:80,weight:5},
            {item:"762mm",count:80,weight:5},
            {item:"556mm",count:80,weight:5},
            {item:"50cal",count:40,weight:0.3},
            {item:"308sub",count:10,weight:0.2},
            {item:"gasoline",count:10,weight:0.2},
            {item:"explosive_ammo",count:4,weight:0.2},
        ],
        //Armors And Backpacks
        "armors":[
            {item:"basic_vest",weight:10},
            {item:"regular_vest",weight:1},
            {item:"tactical_vest",weight:0.05},

            {item:"basic_helmet",weight:10},
            {item:"regular_helmet",weight:1},
            {item:"tactical_helmet",weight:0.05},
        ],
        "backpacks":[
            {item:"basic_pack",weight:10},
            {item:"regular_pack",weight:1},
            {item:"tactical_pack",weight:0.05},
        ],
        "equipments":[
            {item:"basic_vest",weight:10},
            {item:"regular_vest",weight:1},
            {item:"tactical_vest",weight:0.05},

            {item:"basic_helmet",weight:10},
            {item:"regular_helmet",weight:1},
            {item:"tactical_helmet",weight:0.05},

            {item:"basic_pack",weight:10},
            {item:"regular_pack",weight:1},
            {item:"tactical_pack",weight:0.05},
        ],
        "special_equipments":[
            {item:"basic_vest",weight:10},
            {item:"regular_vest",weight:3},
            {item:"tactical_vest",weight:0.15},

            {item:"basic_helmet",weight:10},
            {item:"regular_helmet",weight:1},
            {item:"tactical_helmet",weight:0.15},

            {item:"basic_pack",weight:10},
            {item:"regular_pack",weight:1},
            {item:"tactical_pack",weight:0.15},
        ],
        "airdrop_equipments":[
            {item:"tactical_vest",weight:1},
            {item:"tactical_helmet",weight:1},
            {item:"tactical_pack",weight:1},
        ],
        //Loot Tables
        "ground_loot":[
            {weight:1.5,table:"ammos"},
            {weight:1,table:"equipments"},
            {weight:0.5,table:"guns"},
            {weight:0.01,table:"melees"},
        ],
        "wood_crate":[
            [{weight:10,table:"ammos"},{weight:1,table:""}],
            [{weight:10,table:"consumibles"},{weight:1,table:""}],
            [{weight:9.5,table:"equipments"},{weight:1,table:""}],
            [{weight:1,table:"guns"}],
            [{weight:60,table:""},{weight:1,table:"melees"}],
        ],
        "copper_crate":[
            [{weight:10,table:"special_ammos"},{weight:1,table:""}],
            [{weight:10,table:"consumibles"},{weight:1,table:""}],
            [{weight:9.5,table:"special_equipments"},{weight:1,table:""}],
            [{weight:1,table:"special_guns"}],
            [{weight:40,table:""},{weight:1,table:"melees"}],
        ],
        "iron_crate":[
            [{weight:10,table:"special_ammos",count:2},{weight:1,table:""}],
            [{weight:10,table:"consumibles"},{weight:1,table:""}],
            [{weight:1,table:"airdrop_equipments"}],
            [{weight:1,table:"mythic_guns"}],
            [{weight:5,table:""},{weight:1,table:"melees"}],
        ],
        "gold_crate":[
            [{weight:10,table:"special_ammos",count:2},{weight:1,table:""}],
            [{weight:10,table:"consumibles",count:2},{weight:1,table:""}],
            [{weight:10,table:"airdrop_equipments"},{weight:1,count:2,table:"airdrop_equipments"}],
            [{weight:10,table:"legendary_guns"},{weight:1,table:"mythic_guns"}],
            [{weight:1,table:"melees"}],
        ],
        //Animals
        "animal_medium":[
            [{weight:1,count:1,table:"special_consumibles"}],
            [{weight:10,count:1,table:""},{weight:1,count:1,table:"ammos"}],
        ]
    },
    biome:NormalBiome,
    generation:{
        island:{
            size:v2.new(500,500),
            ground_loot:[{count:80,table:"ground_loot"}],
            spawn:[
                [
                    {id:"container_1",count:25},
                    {id:"container_2",count:25},
                    {id:"oak_tree",count:2700}, //90% of 3000
                    {id:"stone",count:1800}, //90% of 2000
                    {id:"bush",count:1350}, //90% of 1500
                    {id:"wood_crate",count:630},//90% of 700
                    {id:"copper_crate",count:20},
                    {id:"iron_crate",count:1},
                    {id:"gold_crate",count:1},
                    {id:"barrel",count:630}, //90% of 700
                ]
            ],
            terrain:{
                base:FloorType.Water,
                rivers:{
                    divisions:100,
                    spawn_floor:1,
                    expansion:32,
                    defs:[
                        {
                            rivers:[
                                {sub_river_width:2,width:7,width_variation:1,sub_river_chance:0.5},
                                {sub_river_width:1,width:8,width_variation:1,sub_river_chance:0.1},
                            ],
                            weight:10
                        },
                        {
                            rivers:[
                                {sub_river_width:3,width:15,width_variation:1,sub_river_chance:0.9},
                            ],
                            weight:1
                        }
                    ]
                },
                floors:[
                    {
                        padding:30,
                        type:FloorType.Sand,
                        spacing:3,
                        variation:3,
                    },
                    {
                        padding:14,
                        type:FloorType.Grass,
                        spacing:3,
                        variation:3,
                    }
                ]
            }
        }
    },
}
export const NormalLobby:MapDef={
    loot_tables:NormalMap.loot_tables,
    generation:{
        island:{
            size:v2.new(100,100),
            ground_loot:[{count:20,table:"ground_loot"}],
            spawn:[
                [
                    {id:"oak_tree",count:40},
                    {id:"stone",count:30},
                    {id:"bush",count:20},
                    {id:"wood_crate",count:15},
                    {id:"copper_crate",count:3},
                    {id:"barrel",count:8},

                    /*{id:"pig",count:10},
                    {id:"chicken",count:10}*/
                ]
            ],
            terrain:{
                base:FloorType.Water,
                rivers:{
                    divisions:30,
                    spawn_floor:1,
                    expansion:12,
                    defs:[
                        {
                            rivers:[
                                {sub_river_width:2,width:2,width_variation:1,sub_river_chance:0.5},
                                {sub_river_width:1,width:3,width_variation:1,sub_river_chance:0.1},
                            ],
                            weight:10
                        },
                        {
                            rivers:[
                                {sub_river_width:3,width:4,width_variation:1,sub_river_chance:0.9},
                            ],
                            weight:1
                        }
                    ]
                },
                floors:[
                    {
                        padding:15,
                        type:FloorType.Sand,
                        spacing:3,
                        variation:1.3,
                    },
                    {
                        padding:10,
                        type:FloorType.Grass,
                        spacing:3,
                        variation:1.3,
                    }
                ]
            }
        },
    },
    biome:NormalBiome,
}
export const SnowBiome:BiomeDef={
    floors:{
        [FloorType.Sand]:{
            color:0x8a979e
        }
    },
    biome_skin:"snow",
    assets:["normal","christmas"],
    ambient:{
        particles:[],
        rain:false,
        snow:true,
        sound:"snowstorm_ambience"
    }
}
export const SnowMap:MapDef={
    loot_tables:{...NormalMap.loot_tables,
        christmas_tree:[
            [{item:"kar98k",weight:10},{item:"awp",weight:1}],
            [{item:"m870",weight:10},{item:"spas12",weight:1}],

            [{table:"special_healings",count:3,weight:6}],
            [{table:"ammos",count:6,weight:6}],
            [{table:"special_equipments",count:3,weight:6}],
            [{table:"airdrop_equipments",weight:6}],
            [{table:"melees",count:1,weight:6}],
        ]
    },
    default_floor:FloorType.Ice,
    biome:SnowBiome,
    generation:{
        island:{
            size:v2.new(500,500),
            ground_loot:[{count:80,table:"ground_loot"}],
            spawn:[
                [
                    {id:"christmas_tree",count:3},
                    {id:"container_1",count:25},
                    {id:"container_2",count:25},
                    {id:"oak_tree",count:2700}, //90% of 3000
                    {id:"stone",count:1800}, //90% of 2000
                    {id:"bush",count:1350}, //90% of 1500
                    {id:"wood_crate",count:630},//90% of 700
                    {id:"copper_crate",count:20},
                    {id:"iron_crate",count:1},
                    {id:"gold_crate",count:1},
                    {id:"barrel",count:630}, //90% of 700
                ]
            ],
            terrain:{
                base:FloorType.Ice,
                rivers:{
                    divisions:100,
                    spawn_floor:1,
                    expansion:32,
                    floor:FloorType.Ice,
                    defs:[
                        {
                            rivers:[
                                {sub_river_width:5,width:7,width_variation:1,sub_river_chance:0.5},
                                {sub_river_width:5,width:8,width_variation:1,sub_river_chance:0.1},
                            ],
                            weight:10
                        },
                        {
                            rivers:[
                                {sub_river_width:10,width:15,width_variation:1,sub_river_chance:0.9},
                            ],
                            weight:1000
                        }
                    ]
                },
                floors:[
                    {
                        padding:30,
                        type:FloorType.Sand,
                        spacing:3,
                        variation:3,
                    },
                    {
                        padding:14,
                        type:FloorType.Snow,
                        spacing:3,
                        variation:3,
                    }
                ]
            }
        }
    },
}